### ISSUE TITLE
Number of doses is not generalized

### ISSUE THREAD

**Issue by ghost** [datarail/datarail#33]
The number of doses parameter does not work in the set_dosing function. It looks like the number is currently set to 9.

**Comment by smkartik** [comment]
Maximum is set to 9.  If num doses < 9, then doses will be removed starting from lowest moving to higher doses.

**Comment by ghost** [comment]
Might be a nice option to parameterize beyond 9 doses, as we have already needed to do so for some experiments.

**Comment by smkartik** [comment]
Can you give an example dose range? We typically set it up and to be half log steps across 3-5 order  of magnitude which can be captured in 9 or fewer doses
