### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by Hellengeremias** [datarail/datarail#40]
Dear @smkartik 

I am new in python environment and I am trying to reproduce the Computational workflow for design of dose-response experiments.

I could not find the datasets plate_level_metadata.csv and dose_response_layout_metadata.csv on examples file.

Any help will be much appreciated.

Thank you.

Best,
Hellen

**Comment by smkartik** [comment]
Hello Hellen,

Please refer to the example notebook in the link below instead of the Readme.
https://github.com/datarail/datarail/blob/master/datarail/examples/create_plate_layout.ipynb

**Comment by Hellengeremias** [comment]
Dear @smkartik ,

Thank you for your quickly reply.

Best,
Hellen
